services:
  kafka:
    image: kafka-kraft:latest
    container_name: kafka-kraft
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9092,INSIDE://kafka:9094
      KAFKA_LISTENERS: OUTSIDE://:9092,CONTROLLER://:9093,INSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "example:1:1"
    restart: unless-stopped
